### PR TITLE
Medeco Updates

### PR DESCRIPTION
**Pull request by adventuredan**
Added M3.scad for generating Medeco M3 keys
Added m3_slider module to keygen.scad for cutting the M3 slider.
Updated the Medeco_Classic.scad to use the proper .030" cut depth increments instead of Biaxials' .025"
added L,C,R cut angles to Medeco_Biaxial.scad as these sometimes utilize the Classic center cuts. (possibly not in combination with KBQMDS?)
Added "M3" keyway to medeco.svg

### CODE REVIEW

**Comment by adventuredan** [comment]
First time forking a project and contibuting at all through github. 

Let me know if there's any best practice or naming and description conventions i should be aware of.

**Comment by adventuredan** [comment]
Accidentally uploaded the updated files to the main folder. Then again as .txt files accidentally. Should be all good now

**Review by charely6 — APPROVED** [review]
Everything looks good to me.

**Review by charely6 — COMMENTED** [review]
Looks good to me

**Pull request merged**
